module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/pages/**/*.html'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f2f0ed',
        'on-surface-variant': '#55433c',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'tertiary-container': '#a96420',
        'surface-tint': '#9b4422',
        primary: '#984220',
        'on-tertiary': '#ffffff',
        secondary: '#006a60',
        'surface-container-high': '#eae8e5',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#7c2e0c',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#380d00',
        'on-primary-container': '#fffbff',
        'on-tertiary-fixed': '#2e1500',
        'tertiary-fixed': '#ffdcc2',
        surface: '#fbf9f6',
        'surface-variant': '#e4e2df',
        'primary-fixed-dim': '#ffb59b',
        'on-secondary-fixed': '#00201c',
        'on-error': '#ffffff',
        'on-secondary-container': '#006f64',
        'surface-container-highest': '#e4e2df',
        background: '#fbf9f6',
        'on-secondary-fixed-variant': '#005048',
        outline: '#89726b',
        'secondary-container': '#86f2e2',
        'outline-variant': '#dcc1b8',
        'surface-bright': '#fbf9f6',
        'secondary-fixed': '#89f5e5',
        'on-tertiary-fixed-variant': '#6d3a00',
        'primary-container': '#b75a36',
        'surface-dim': '#dbdad7',
        tertiary: '#8b4c05',
        'tertiary-fixed-dim': '#ffb77b',
        'primary-fixed': '#ffdbcf',
        'on-secondary': '#ffffff',
        'inverse-surface': '#30312f',
        'surface-container': '#efeeeb',
        'on-tertiary-container': '#fffbff',
        'surface-container-low': '#f5f3f0',
        'secondary-fixed-dim': '#6bd8c9',
        'on-background': '#1b1c1a',
        'inverse-primary': '#ffb59b',
        'on-surface': '#1b1c1a',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
        serif: ['Merriweather', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};